title = "Big Data Analytics - Part II"
lesson_number = 10

objectives = []

resources = []

readings = [
    "Chapter 5 in **Big Data Science and Analytics**",
]

supplemental = []

submission_instructions = ""
