title = "Big Data Analytics - Part I"
lesson_number = 9

objectives = []

resources = []

readings = [
    "Chapter 5 in **Big Data Science and Analytics**",
]

supplemental = []

submission_instructions = ""
