title = "Big Data Storage and Batch Processing"
lesson_number = 6

objectives = []

resources = []

readings = [
    "Chapters 6 & 7 in **Big Data Science and Analytics**",
]

supplemental = []

submission_instructions = ""
