title = "Big Data Visualization"
lesson_number = 11

objectives = []

resources = []

readings = [
    "Chapter 5 in **Big Data Science and Analytics**",
]

supplemental = []

submission_instructions = ""
